apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if external access is needed
  selector:
    app: haproxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080